<?php
/**
 * Created by PhpStorm.
 * User: phu.pham
 * Date: 23/1/2018
 * Time: 1:48 PM
 */
?>


<div class="modal fade" id="signup_modal" tabindex="-1" role="dialog">

    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <div class="modal-body modal-body-sub_agile">

                <div class="col-md-8 modal_body_left modal_body_left1">

                    <h3 class="agileinfo_sign" style="padding-bottom: 15px; border-bottom: 1px solid;   ">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        Đăng ký tài khoản
                    </h3>

                    <form action="#" method="post">

                        <div class="styled-input agile-styled-input-top">
                            <input type="text" name="Name" required="">
                            <label>Tên quý khách</label>
                            <span></span>
                        </div>

                        <div class="styled-input">
                            <input type="email" name="Email" required="">
                            <label>Địa chỉ email</label>
                            <span></span>
                        </div>

                        <div class="styled-input">
                            <input type="password" name="password" required="">
                            <label>Nhập mật khẩu</label>
                            <span></span>
                        </div>

                        <div class="styled-input">
                            <input type="password" name="Confirm Password" required="">
                            <label>Nhập lại mật khẩu</label>
                            <span></span>
                        </div>

                        <input type="submit" value="Đăng ký ngay !">

                    </form>


                    <div class="clearfix"></div>

                    <p style="text-align: justify;margin-top: 10px;">
                        Bạn phải đồng ký với các điều khoản và quy định sửa dụng của <a href="http://eco-idea.vn">eco-idea.vn</a>
                        sau khi hoàn tất đăng ký. Xem chi tiết <a href="http://eco-idea.vn">các điều khoản</a> tại đây.
                    </p>

                </div>

                <div class="col-md-4 modal_body_right modal_body_right1">
                    <img src="<?php echo $this->basePath('images/frontend/signup_right_banner.jpg'); ?>" alt=" "/>
                </div>

                <div class="clearfix"></div>

            </div>
        </div>
        <!-- //Modal content-->
    </div>
</div>
