<?php
/**
 * Created by PhpStorm.
 * User: phu.pham
 * Date: 23/2/2018
 * Time: 11:06 AM
 */


$this->headTitle('Cập nhật người dùng');

//$this->mainMenu()->setActiveItemId('lien-he');

$this->pageBreadcrumbs()->setItems([
    'Quản trị' => $this->url('admin'),
    'Danh sách người dùng' => $this->url('admin/manage-user', ['action' => 'index']),
    'Cập nhật người dùng' => $this->url('admin/manage-user',
        ['action' => 'edit', 'id' => $user->getId()]),
]);

$this->pageBreadcrumbs()->setTopImageBanner(
    $this->basePath('images/frontend/admin_manage_user_top_banner.jpg'));

$this->pageBreadcrumbs()->setPageLabel('Cập nhật người dùng');

//init plugins
if (isset($initPlugins)) {
    echo $this->partial('app/init_plugin', ['initPlugins' => $initPlugins]);
}

$form->setAttribute('id', 'change_user_password_form');

$form->get('new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter new password'
]);

$form->get('confirm_new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Re-enter new password'
]);


$form->prepare();

?>

<!-- breadcrumbs -->
<?= $this->pageBreadcrumbs()->render(); ?>

<div class="container">

    <div class="container_main_body">

        <h5>
            <i class="fa fa-edit"></i>
            Mật khẩu: <?= $this->escapeHtml($user->getEmail()) ?>
        </h5>

        <div class="top_menu_bar">

            <a class="btn btn-app" onclick="document.getElementById('change_user_password_form').submit();">
                <i class="fa fa-save"></i>
                Lưu lại
            </a>

            <a href="<?= $this->url('admin/manage-user', ['action' => 'change-password', 'id' => $user->getId()]); ?>"
               class="btn btn-app">
                <i class="fa fa-refresh"></i>
                Refresh
            </a>

            <a class="btn btn-app" href="<?= $this->url('admin/manage-user', ['action' => 'index']); ?>">
                <i class="fa fa-sign-out"></i>
                Thoát
            </a>

        </div>

        <div class="body_content">

            <div class="row">

                <div class="col-md-12">

                    <!-- breadcrumbs -->
                    <?= $this->message()->render(); ?>

                    <?= $this->form()->openTag($form); ?>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('new_password')); ?>
                        <?= $this->formElement($form->get('new_password')); ?>
                        <?= $this->formElementErrors($form->get('new_password')); ?>
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('confirm_new_password')); ?>
                        <?= $this->formElement($form->get('confirm_new_password')); ?>
                        <?= $this->formElementErrors($form->get('confirm_new_password')); ?>
                    </div>

                    <?= $this->formElement($form->get('csrf')); ?>

                    <?= $this->form()->closeTag(); ?>

                </div>

            </div>

        </div>


    </div>

</div>





