<?php
/**
 * Created by PhpStorm.
 * User: phu.pham
 * Date: 23/1/2018
 * Time: 11:06 AM
 */
?>

<div class="header" id="home">

    <div class="container">
        <?php echo $this->topMenu()->renderItems(); ?>
    </div>

</div>

<!-- header-bot -->
<div class="header-bot">

    <div class="header-bot_inner_wthreeinfo_header_mid">

        <div class="col-md-4 header-middle">

            <form action="#" method="post">
                <input type="search" name="search"
                       placeholder="Tìm kiếm thông tin..." required="">
                <input type="submit" value=" ">
                <div class="clearfix"></div>
            </form>

        </div>

        <!-- header-bot -->
        <div class="col-md-4 logo_agile">

            <h1>

                <a href="http://eco-idea.vn/"><span>Eco</span>Idea
                    <i class="glyphicon glyphicon-menu-right" aria-hidden="true"></i>
                    <div style="font-size: 20px; margin-top: 15px;">Giải pháp cho CMCM 4.0</div>
                </a>

            </h1>

        </div>

        <!-- header-bot -->
        <div class="col-md-4 agileits-social top_content">

            <ul class="social-nav model-3d-0 footer-social w3_agile_social">

                <li class="share">
                    Chia sẽ eco-idea.vn:
                </li>

                <li><a href="#" class="facebook">
                        <div class="front"><i class="fa fa-facebook" aria-hidden="true"></i></div>
                        <div class="back"><i class="fa fa-facebook" aria-hidden="true"></i></div>
                    </a></li>
                <li><a href="#" class="twitter">
                        <div class="front"><i class="fa fa-twitter" aria-hidden="true"></i></div>
                        <div class="back"><i class="fa fa-twitter" aria-hidden="true"></i></div>
                    </a></li>
                <li><a href="#" class="instagram">
                        <div class="front"><i class="fa fa-instagram" aria-hidden="true"></i></div>
                        <div class="back"><i class="fa fa-instagram" aria-hidden="true"></i></div>
                    </a></li>
                <li><a href="#" class="pinterest">
                        <div class="front"><i class="fa fa-linkedin" aria-hidden="true"></i></div>
                        <div class="back"><i class="fa fa-linkedin" aria-hidden="true"></i></div>
                    </a></li>

            </ul>


        </div>
        <div class="clearfix"></div>

    </div>

</div>
