<?php

$this->headTitle('Đăng nhập');

//$this->mainMenu()->setActiveItemId('lien-he');

$this->pageBreadcrumbs()->setItems([
    'Trang chủ' => $this->url('trang-chu'),
    'Người dùng' => $this->url('users'),
    'Đăng nhập' => $this->url('login'),
]);

$this->pageBreadcrumbs()->setTopImageBanner(
    $this->basePath('images/frontend/login_top_banner.jpg'));

$this->pageBreadcrumbs()->setPageLabel('Đăng nhập');

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Email address',
    'required' => true,
    'autofocus' => true
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Password',
    'required' => true,
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

?>

<!-- breadcrumbs -->
<?= $this->pageBreadcrumbs()->render(); ?>


<div class="banner_bottom_agile_info">

    <div class="container">

        <div class="agile-contact-grids">

            <!-- contact form -->
            <div class="col-md-6 login-form">

                <h3 class="bars">Vui lòng đăng nhập</h3>

                <form class="form-signin" method="post">

                    <?php if ($isLoginError): ?>
                        <div class="alert alert-warning" role="alert">
                            Thông tin đăng nhập không chính xác !
                            <a href="<?= $this->url('reset-password') ?>">Quên mật khẩu ?</a>
                        </div>
                    <?php endif; ?>


                    <div class="input-group input-group-lg w3_w3layouts">
                        <span class="input-group-addon" id="basic-addon_1"><i class="fa fa-user"></i></span>
                        <?= $this->formLabel($form->get('email')); ?>
                        <?= $this->formElement($form->get('email')); ?>
                    </div>


                    <div class="input-group input-group-lg w3_w3layouts">
                        <span class="input-group-addon" id="basic-addon_2"><i class="fa fa-lock"></i></span>
                        <?= $this->formLabel($form->get('password')); ?>
                        <?= $this->formElement($form->get('password')); ?>
                    </div>


                    <div class="checkbox">
                        <label>
                            <?= $this->formElement($form->get('remember_me')); ?>
                            <?php echo $form->get('remember_me')->getOption('label'); ?>
                        </label>
                    </div>

                    <?= $this->formElement($form->get('redirect_url')); ?>
                    <?= $this->formElement($form->get('csrf')) ?>

                    <button class="btn btn-lg btn-primary btn-block" type="submit">Đăng nhập</button>

                </form>

            </div>

            <div class="col-md-6">
                <h4>Thông tin đăng nhập</h4>
            </div>

            <div class="clearfix"></div>

        </div>

    </div>

</div>
