<?php
/**
 * Created by PhpStorm.
 * User: phu.pham
 * Date: 23/1/2018
 * Time: 2:00 PM
 */
?>
<div id="myCarousel" class="carousel slide" data-ride="carousel">

    <!-- Indicators -->
    <ol class="carousel-indicators">

        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1" class=""></li>

    </ol>

    <div class="carousel-inner" role="listbox">

        <div class="item active">
            <div class="container">
                <div class="carousel-caption">
                    <h3>NÔNG NGHIỆP <span>THÔNG MINH</span></h3>
                    <p>Tiện lợi, hiệu quả, chi phí hợp lý</p>
                    <a class="hvr-outline-out button2" href="mens.html">Tìm hiểu thêm</a>
                </div>
            </div>
        </div>

        <div class="item item2">
            <div class="container">
                <div class="carousel-caption">
                    <h3>CÁCH MẠNG 4.0 TRONG <span>NÔNG NGHIỆP</span></h3>
                    <p>Tiện lợi, hiệu quả, chi phí hợp lý</p>
                    <a class="hvr-outline-out button2" href="mens.html">Tìm hiểu thêm</a>
                    <a class="hvr-outline-out button2" href="mens.html">Đặt mua sản phẩm</a>
                </div>
            </div>
        </div>


    </div>

    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>

    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>

</div>
