<?php

$this->headTitle('Thay đổi mật khẩu');

$this->pageBreadcrumbs()->setItems([
    'Người dùng' => $this->url('users'),
    'Thay đổi mật khẩu' => $this->url('users',
        ['action' => 'change-password']),
]);

$this->pageBreadcrumbs()->setTopImageBanner(
    $this->basePath('images/frontend/user_home_page_banner.jpg'));

$this->pageBreadcrumbs()->setPageLabel('Thay đổi mật khẩu');

//init plugins
if (isset($initPlugins)) {
    echo $this->partial('app/init_plugin', ['initPlugins' => $initPlugins]);
}

$form->setAttribute('id', 'change_user_password_form');

$form->get('old_password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Nhập mật khẩu cũ'
    ]);

$form->get('new_password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Nhập mật khẩu mới'
    ]);

$form->get('confirm_new_password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Nhập lại mật khẩu'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();

?>

<!-- breadcrumbs -->
<?= $this->pageBreadcrumbs()->render(); ?>

<div class="container">

    <div class="container_main_body">

        <h5>
            <i class="fa fa-lock"></i>
            Thay đổi mật khẩu
        </h5>

        <div class="top_menu_bar">

            <a class="btn btn-app" onclick="document.getElementById('change_user_password_form').submit();">
                <i class="fa fa-save"></i>
                Thay đổi
            </a>

            <a href="<?= $this->url('users', ['action' => 'change-password', 'id' => $user->getId()]); ?>"
               class="btn btn-app">
                <i class="fa fa-refresh"></i>
                Refresh
            </a>

            <a class="btn btn-app" href="<?= $this->url('users', ['action' => 'index']); ?>">
                <i class="fa fa-sign-out"></i>
                Thoát
            </a>

        </div>

        <div class="body_content">

            <div class="row">

                <div class="col-md-12">

                    <!-- message -->
                    <?= $this->message()->render(); ?>

                    <?= $this->form()->openTag($form); ?>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('old_password')); ?>
                        <?= $this->formElement($form->get('old_password')); ?>
                        <?= $this->formElementErrors($form->get('old_password')); ?>
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('new_password')); ?>
                        <?= $this->formElement($form->get('new_password')); ?>
                        <?= $this->formElementErrors($form->get('new_password')); ?>
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('confirm_new_password')); ?>
                        <?= $this->formElement($form->get('confirm_new_password')); ?>
                        <?= $this->formElementErrors($form->get('confirm_new_password')); ?>
                    </div>

                    <?= $this->formElement($form->get('csrf')); ?>

                    <?= $this->form()->closeTag(); ?>

                </div>

            </div>

        </div>


    </div>

</div>