<?= $this->doctype() ?>

<html lang="en">

<head>

    <meta charset="utf-8">

    <!-- append to title -->
    <?= $this->headTitle('Eco-Idea')
        ->setSeparator(' - ')->setAutoEscape(false) ?>

    <!-- metadata -->
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <script type="application/x-javascript"> addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>

    <!-- styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/images/frontend/logo/favicon/favicon.ico']); ?>

    <link href="<?php echo $this->basePath('css/bootstrap.css'); ?>" rel="stylesheet" type="text/css" media="all"/>
    <link href="<?php echo $this->basePath('css/style.css'); ?>" rel="stylesheet" type="text/css" media="all"/>
    <link href="<?php echo $this->basePath('css/custom.css'); ?>" rel="stylesheet" type="text/css" media="all"/>
    <link href="<?php echo $this->basePath('css/font-awesome.css'); ?>" rel="stylesheet">
    <link href="<?php echo $this->basePath('css/easy-responsive-tabs.css'); ?>" rel='stylesheet' type='text/css'/>

    <!-- Google's fonts -->
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
    <link
            href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic'
            rel='stylesheet' type='text/css'>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.js'))
        ->prependFile($this->basePath('js/jquery-2.1.4.min.js'))
    ?>

</head>

<body>

<!-- header -->
<?php echo $this->partial('layout/partials/header'); ?>

<!-- content page -->
<?= $this->content; ?>

<!-- inline scripts -->
<?= $this->inlineScript() ?>

<!-- footer -->
<?php echo $this->partial('layout/partials/footer'); ?>


<!-- toTopHover -->
<a href="#home" class="scroll" id="toTop" style="display: block;">
    <span id="toTopHover" style="opacity: 1;"> </span>
</a>

</body>

<!-- footer scripts -->
<script src="<?php echo $this->basePath('js/modernizr.custom.js'); ?>" type="text/javascript"></script>

<script src="<?php echo $this->basePath('js/minicart.min.js'); ?>" type="text/javascript"></script>

<script type="text/javascript">
    // Mini Cart
    paypal.minicart.render({
        action: '#'
    });

    if (~window.location.search.indexOf('reset=true')) {
        paypal.minicart.reset();
    }
</script>

<script src="<?php echo $this->basePath('js/jquery.waypoints.min.js'); ?>"></script>

<script src="<?php echo $this->basePath('js/jquery.countup.js'); ?>"></script>

<!-- start-smoth-scrolling -->
<script src="<?php echo $this->basePath('js/move-top.js'); ?>" type="text/javascript"></script>

<script src="<?php echo $this->basePath('js/jquery.easing.min.js'); ?>" type="text/javascript"></script>

<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(".scroll").click(function (event) {
            event.preventDefault();
            $('html,body').animate({scrollTop: $(this.hash).offset().top}, 1000);
        });
    });
</script>

<!-- here stars scrolling icon -->
<script type="text/javascript">
    $(document).ready(function () {
        $().UItoTop({easingType: 'easeOutQuart'});
    });
</script>

</html>
