<?php
/**
 * Created by PhpStorm.
 * User: phu.pham
 * Date: 23/1/2018
 * Time: 11:08 AM
 */
?>

<div class="footer">

    <div class="footer_agile_inner_info_w3l">

        <div class="col-md-3 footer-left">

            <h2><a href="http://eco-idea.vn/"><span>Eco</span> Idea</a></h2>

            <p style="text-align: justify">
                <a href="http://eco-idea.vn/">Eco-idea</a> là đơn vị trực thuộc phòng thí nghiệm Trí tuệ Nhân tạo
                (AILab), thuộc Trường ĐH Khoa học Tự nhiên (ĐH KHTN) TP.HCM được thành lập ngày 01/08/2008 với kinh phí
                đầu tư ban đầu khoảng gần 7 tỷ VNĐ từ ngân sách ĐHQG-HCM.
            </p>

            <ul class="social-nav model-3d-0 footer-social w3_agile_social two">
                <li><a href="#" class="facebook">
                        <div class="front"><i class="fa fa-facebook" aria-hidden="true"></i></div>
                        <div class="back"><i class="fa fa-facebook" aria-hidden="true"></i></div>
                    </a></li>
                <li><a href="#" class="twitter">
                        <div class="front"><i class="fa fa-twitter" aria-hidden="true"></i></div>
                        <div class="back"><i class="fa fa-twitter" aria-hidden="true"></i></div>
                    </a></li>
                <li><a href="#" class="instagram">
                        <div class="front"><i class="fa fa-instagram" aria-hidden="true"></i></div>
                        <div class="back"><i class="fa fa-instagram" aria-hidden="true"></i></div>
                    </a></li>
                <li><a href="#" class="pinterest">
                        <div class="front"><i class="fa fa-linkedin" aria-hidden="true"></i></div>
                        <div class="back"><i class="fa fa-linkedin" aria-hidden="true"></i></div>
                    </a></li>
            </ul>

        </div>

        <div class="col-md-9 footer-right">

            <div class="sign-grds">

                <div class="col-md-4 sign-gd">

                    <h4>Danh mục</h4>

                    <ul>

                        <li>
                            <a href="index.html">Trang chủ</a>
                        </li>

                        <li>
                            <a href="mens.html">Giới thiệu</a>
                        </li>

                        <li>
                            <a href="womens.html">Sản phẩm</a>
                        </li>

                        <li>
                            <a href="about.html">Liên hệ</a>
                        </li>

                    </ul>

                </div>

                <div class="col-md-5 sign-gd-two">

                    <h4>Thông tin liên hệ</span></h4>

                    <div class="w3-address">

                        <div class="w3-address-grid">

                            <div class="w3-address-left">
                                <i class="fa fa-phone" aria-hidden="true"></i>
                            </div>

                            <div class="w3-address-right">

                                <h6>Số điện thoại</h6>
                                <p>(84)-28-38303625</p>

                            </div>

                            <div class="clearfix"></div>

                        </div>

                        <div class="w3-address-grid">

                            <div class="w3-address-left" style="color: #ffffff;">
                                <i class="fa fa-fax" aria-hidden="true"></i>
                            </div>

                            <div class="w3-address-right">

                                <h6>Số Fax:</h6>
                                <p>(84)-28-38325926</p>

                            </div>

                            <div class="clearfix"></div>

                        </div>

                        <div class="w3-address-grid">
                            <div class="w3-address-left">
                                <i class="fa fa-envelope" aria-hidden="true"></i>
                            </div>
                            <div class="w3-address-right">
                                <h6>Địa chỉ email:</h6>
                                <p>Email :
                                    <a href="mailto:info@eco-idea.vn">
                                        info@eco-idea.vn
                                    </a>
                                </p>
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <div class="w3-address-grid">

                            <div class="w3-address-left">
                                <i class="fa fa-map-marker" aria-hidden="true"></i>
                            </div>

                            <div class="w3-address-right">
                                <h6>Địa chỉ liên hệ:</h6>
                                <p style="text-align: justify; letter-spacing: 0px;">
                                    PTN AILab: I64, tòa nhà I, Đại học Khoa Học Tự Nhiên TP. HCM, ĐHQG-HCM, 227 Nguyễn
                                    Văn Cừ, Quận 5
                                </p>
                            </div>

                            <div class="clearfix"></div>

                        </div>

                    </div>

                </div>

                <div class="col-md-3 sign-gd flickr-post">
                    <h4>Các đơn vị tài trợ</span></h4>

                    <ul>

                        <li>
                            <a href="http://www.vnuhcm.edu.vn/">
                                <img src="<?php echo $this->basePath('images/frontend/logo/dhqg-logo.jpg') ?>"
                                     alt=" " class="img-responsive" style="background-color: #ffffff;"/>
                        </li>

                        <li>
                            <a href="http://web.hcmus.edu.vn/">
                                <img src="<?php echo $this->basePath('images/frontend/logo/logo-khtn.png') ?>"
                                     alt=" " class="img-responsive" style="background-color: #ffffff;"/>
                        </li>


                        <li>
                            </a><a href="http://www.itec.hcmus.edu.vn/vn/index.php">
                                <img src="<?php echo $this->basePath('images/frontend/logo/itec-logo.jpg') ?>"
                                     alt=" " class="img-responsive" style="background-color: #ffffff;"/>
                            </a>
                        </li>

                    </ul>

                </div>

                <div class="clearfix"></div>

            </div>

        </div>

        <div class="clearfix"></div>

        <div class="agile_newsletter_footer">

            <div class="col-sm-6 newsleft">
                <h3>ĐĂNG KÝ ĐỂ NHẬN THÔNG TIN !</h3>
            </div>

            <div class="col-sm-6 newsright">
                <form action="#" method="post">
                    <input type="email" placeholder="Nhập địa chỉ email của bạn..." name="email" required="">
                    <input type="submit" value="Đăng ký">
                </form>

            </div>

            <div class="clearfix"></div>

        </div>

        <p class="copy-right">&copy 2018 Bản quyền thuộc về eco-idea.vn. Thiết kế và triển khai bởi
            <a href="http://eco-idea.vn">eco-idea.vn</a>
        </p>

    </div>

</div>
