<?php
/**
 * Created by PhpStorm.
 * User: phu.pham
 * Date: 23/1/2018
 * Time: 11:06 AM
 */
?>

<!-- top header -->
<?php echo $this->partial('layout/partials/headers/top_header'); ?>


<!-- banner -->
<div class="ban-top">

    <div class="container">

        <!-- top menus -->
        <?php echo $this->partial('layout/partials/menus/top_menu'); ?>

        <div class="clearfix"></div>

    </div>

</div>


<!-- Login modal -->
<?php echo $this->partial('layout/partials/modals/login_popup'); ?>

<!-- Signup modal -->
<?php echo $this->partial('layout/partials/modals/signup_popup'); ?>


