<?php
/**
 * Created by PhpStorm.
 * User: phu.pham
 * Date: 22/2/2018
 * Time: 4:36 PM
 */
?>

<?php if (isset($initPlugins)): ?>

    <!-- datatables -->
    <?php if (in_array('datatables', $initPlugins)): ?>

        <link href="<?php echo $this->basePath('plugins/datatables/1.10.12/jquery.dataTables.min.css'); ?>"
              rel="stylesheet"/>
        <link href="<?php echo $this->basePath('plugins/datatables/1.10.12/buttons.dataTables.min.css'); ?>"
              rel="stylesheet"/>
        <link
            href="<?php echo $this->basePath('plugins/datatables/1.10.12/responsive/responsive.dataTables.min.css'); ?>"
            rel="stylesheet"/>
        <link href="<?php echo $this->basePath('plugins/datatables/1.10.12/select/select.dataTables.min.css'); ?>"
              rel="stylesheet"/>

        <script src="<?php echo $this->basePath('plugins/datatables/1.10.12/jquery.dataTables.min.js'); ?>"
                type="text/javascript"></script>
        <script
            src="<?php echo $this->basePath('plugins/datatables/1.10.12/responsive/dataTables.responsive.min.js'); ?>"
            type="text/javascript"></script>
        <script src="<?php echo $this->basePath('plugins/datatables/1.10.12/select/dataTables.select.min.js'); ?>"
                type="text/javascript"></script>
        <script src="<?php echo $this->basePath('plugins/datatables/1.10.12/dataTables.buttons.min.js'); ?>"
                type="text/javascript"></script>
        <script src="<?php echo $this->basePath('plugins/datatables/1.10.12/buttons.colVis.min.js'); ?>"
                type="text/javascript"></script>

        <!-- custom scripts -->
        <script src="<?php echo $this->basePath('plugins/datatables/eco-idea_datatables.js'); ?>"
                type="text/javascript"></script>

    <?php endif; ?>
    <!-- datatables -->

    <!-- bootstrap-switch -->
    <?php if (in_array('bootstrap-switch', $initPlugins)): ?>
        <link href="<?php echo $this->basePath('plugins/bootstrap-switch/css/bootstrap3/bootstrap-switch.min.css'); ?>"
              rel="stylesheet"
              type="text/css"/>
        <script src="<?php echo $this->basePath('plugins/bootstrap-switch/js/bootstrap-switch.min.js'); ?>"
                type="text/javascript"></script>
    <?php endif; ?>
    <!-- bootstrap-switch -->

    <!-- select2 -->
    <?php if (in_array('select2', $initPlugins)): ?>
        <link href="<?php echo $this->basePath('plugins/select2/4.0.3/css/select2.min.css'); ?>" rel="stylesheet"/>
        <script type="text/javascript"
                src="<?php echo $this->basePath('plugins/select2/4.0.3/js/select2.full.min.js'); ?>"></script>
        <!--<script type="text/javascript"
                src="<?php /*echo $this->basePath('plugins/select2/vendor/js/placeholders.jquery.min.js'); */ ?>"></script>
        <script type="text/javascript" src="<?php /*echo $this->basePath('plugins/select2/js/i18n/es.js'); */ ?>"></script>-->

    <?php endif; ?>
    <!-- select2 -->


<?php endif; ?>

