<?php
/**
 * Created by PhpStorm.
 * User: phu.pham
 * Date: 23/2/2018
 * Time: 1:22 PM
 */

$this->headTitle('Xóa thiết bị');

//$this->mainMenu()->setActiveItemId('lien-he');

$this->pageBreadcrumbs()->setItems([
    'Quản trị' => $this->url('admin'),
    'Thiết bị' => $this->url('admin/manage-device', ['action' => 'index']),
    'Xóa thiết bị' => $this->url('admin/manage-device',
        ['action' => 'remove', 'id' => $device->getId()]),
]);

$this->pageBreadcrumbs()->setTopImageBanner(
    $this->basePath('images/frontend/admin_manage_device_top_banner.jpg'));

$this->pageBreadcrumbs()->setPageLabel('Xóa thiết bị');

//init plugins
if (isset($initPlugins)) {
    echo $this->partial('app/init_plugin', ['initPlugins' => $initPlugins]);
}

?>

<!-- breadcrumbs -->
<?= $this->pageBreadcrumbs()->render(); ?>


<div class="container">

    <div class="container_main_body">

        <h5>
            <i class="fa fa-edit"></i>
            Xóa thiết bị: <?= $this->escapeHtml($device->getDeviceUniqueId()) ?>
        </h5>

        <div class="top_menu_bar">

            <a href="<?= $this->url('admin/manage-device', ['action' => 'remove', 'id' => $device->getId()]); ?>"
               class="btn btn-app">
                <i class="fa fa-refresh"></i>
                Refresh
            </a>

            <a class="btn btn-app" href="<?= $this->url('admin/manage-device', ['action' => 'index']); ?>">
                <i class="fa fa-sign-out"></i>
                Thoát
            </a>

        </div>

        <div class="body_content">

            <div class="row">

                <div class="col-md-12">

                    <form method="post" action="<?= $this->url('admin/manage-device',
                        ['action' => 'remove', 'id' => $device->getId()]); ?>">

                        <div class="alert alert-warning" role="alert">

                            Bạn có xác nhận thiết bị này: <?= $device->getDeviceUniqueId(); ?>, sau khi xóa, mọi thông tin về toàn
                            khoản sẽ không thể phục hồi lại được !

                            <input type="submit" name="remove_confirm" id="remove_confirm"
                                   class="btn-danger" value="Xác nhận xóa">

                        </div>

                    </form>


                </div>

            </div>

            <div class="row">

                <div class="col-md-4">
                    <?php if ($device->getImage()): ?>
                        <img style="max-width: 300px;max-height: 300px"
                             src="<?= $this->basePath('uploads/' . $this->escapeHtml($device->getImage())); ?>">
                    <?php else: ?>
                        <img style="max-width: 300px;max-height: 300px"
                             src="<?= $this->basePath('images/noimage.png'); ?>">
                    <?php endif; ?>
                </div>

                <div class="col-md-8">

                    <table class="table table-striped table-bordered">

                        <tr>
                            <th>
                                <?= $this->translate('Mã'); ?>
                            </th>
                            <td>
                                <?= $this->escapeHtml($device->getId()) ?>
                            </td>
                        </tr>

                        <tr>
                            <th>
                                <?= $this->translate('Mã thiết bị'); ?>
                            </th>
                            <td>
                                <?= $this->escapeHtml($device->getDeviceUniqueId()) ?>
                            </td>
                        </tr>

                        <tr>
                            <th>
                                <?= $this->translate('Ngày tạo'); ?>
                            </th>
                            <td>
                                <?= $this->escapeHtml($device->getDateImplemented()->format('Y/m/d')); ?>
                            </td>
                        </tr>

                        <tr>
                            <th>
                                <?= $this->translate('Tình trạng'); ?>
                            </th>
                            <td>
                                <?= $this->escapeHtml($device->getStatus()); ?>
                            </td>
                        </tr>

                        <tr>
                            <th>
                                <?= $this->translate('Mô tả thiết bị'); ?>
                            </th>
                            <td>
                                <?= $this->escapeHtml($device->getDescription()); ?>
                            </td>
                        </tr>


                    </table>

                </div>

            </div>


        </div>


    </div>

</div>

